spring.application.name=demo

# PostgreSQL (Render External URL)
spring.datasource.url=jdbc:postgresql://dpg-d0pi6f8dl3ps73aqlup0-a.oregon-postgres.render.com:5432/diatozdb
spring.datasource.username=diatozdb_user
spring.datasource.password=cOZCpe7YV3qCSdWEH7ggowFgUYvCxqsq

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=35f3867c1eaefc77da3785745b24684361be8005caf0e65e504e83964ed01ab134d06e9e4d5181880c6e588c97de7302a629ee145139c36a6cf820d087b3d202
jwt.expiration.ms=3600000 


